In [190]:
import pandas as pd
import numpy as np
import datetime
import os, glob, json, csv
import boto3

In [191]:
s3 = boto3.client('s3')

In [192]:
def list_objects(bucket, prefix):
    response = s3.list_objects_v2(Bucket=bucket, Prefix=prefix)
    if 'Contents' in response:
        return [obj['Key'] for obj in response['Contents'] if obj['Key'] != prefix]
    return []

In [193]:
def list_all_objects(bucket, prefix):
    all_objects = []
    continuation_token = None
    
    while True:
        if continuation_token:
            response = s3.list_objects_v2(Bucket=bucket, Prefix=prefix, ContinuationToken=continuation_token)
        else:
            response = s3.list_objects_v2(Bucket=bucket, Prefix=prefix)
        
        if 'Contents' in response:
            all_objects.extend([obj['Key'] for obj in response['Contents']])
        
        if not response.get('NextContinuationToken'):
            break
        
        continuation_token = response['NextContinuationToken']
    
    return all_objects

In [194]:
def load_talent_data(bucket, prefix):
    files = list_all_objects(bucket, prefix)
    data_frames = []
    for file_key in files:
        if file_key.split(".")[-1] == "csv":
            obj = s3.get_object(Bucket=bucket, Key=file_key)
            df = pd.read_csv(obj['Body'])
            file_name = file_key.split("/")[1].split(".")[0][:-10]
            df.insert(1,'filename', file_name, True)
            data_frames.append(df)
        else:
            continue
    return pd.concat(data_frames, ignore_index=True)

In [195]:
talent_data = load_talent_data('data-402-final-project', 'Talent/')

In [196]:
talent_data

,id,filename,name,gender,dob,email,city,address,postcode,phone_number,uni,degree,invited_date,month,invited_by
0,1,April2019,Esme Trusslove,Female,04/08/1994,etrusslove0@google.es,Swindon,22056 Lerdahl Avenue,SN1,+44-295-783-0228,"Saint George's Hospital Medical School, Univer...",2:1,10.0,April 2019,Bruno Bellbrook
1,2,April2019,Matthaeus Audas,Male,NaN,maudas1@mapquest.com,Charlton,263 Nelson Trail,OX12,+44-957-728-0155,Keele University,2:1,30.0,April 2019,Doris Bellasis
2,3,April2019,Cherey Tollfree,Female,08/12/1992,ctollfree2@netvibes.com,Weston,69 Coleman Court,GU32,+44-588-749-6002,"King's College London, University of London",2:1,25.0,April 2019,Gismo Tilling
3,4,April2019,Eryn Speers,Female,NaN,espeers3@shinystat.com,Sutton,0166 Daystar Drive,CT15,+44 148 787 0613,University of Edinburgh,2:1,NaN,NaN,NaN
4,5,April2019,Theadora Berkelay,Female,03/11/1995,tberkelay4@godaddy.com,Upton,6 Mandrake Crossing,WF9,+44 (841) 468-3619,University of Leicester,2:1,2.0,April 2019,Stacey Broad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4686,416,Sept2019,Clyve Gillhespy,Male,15/12/1995,cgillhespybj@buzzfeed.com,Birmingham,33 Almo Avenue,B40,+44-904-343-2218,University of Liverpool,2:1,26.0,SEPT 2019,Bruno Bellbrook
4687,417,Sept2019,Vaclav Pietesch,Male,09/11/1994,vpieteschbk@mac.com,Whitwell,6476 Hoffman Terrace,DL10,+44 455 631 6125,Sheffield Hallam University,2:2,12.0,SEPT 2019,Stacey Broad
4688,418,Sept2019,Kassi Lucio,Female,24/04/1994,kluciobl@exblog.jp,Normanton,06 Fulton Center,LE15,+44-834-342-9323,University of Buckingham,2:1,3.0,SEPT 2019,Fifi Eton
4689,419,Sept2019,Vivianna Letty,Female,NaN,vlettybm@google.com.hk,Sheffield,78314 Fisk Plaza,S1,+44-534-758-3140,Leeds Metropolitan University,1st,19.0,SEPT 2019,Bruno Bellbrook
4690,420,Sept2019,Mercie Groger,Female,10/05/1997,mgrogerbn@timesonline.co.uk,Charlton,5 Toban Circle,OX12,+44-662-239-4688,ifs University College,3rd,12.0,SEPT 2019,Rupert Ripple

In [197]:
#talent_data.isna().sum()

In [198]:
#talent_data[talent_data["invited_by"].isna()]

In [199]:
talent_data.dtypes #["phone_number"].type()

id                int64
filename         object
name             object
gender           object
dob              object
email            object
city             object
address          object
postcode         object
phone_number     object
uni              object
degree           object
invited_date    float64
month            object
invited_by       object
dtype: object

## Phone Numbers Column Cleaning

In [200]:
# to_replace = ["-", " ", "(", ")"]
def clean_phone_numbers(phone_no):
    to_replace = ["-", " ", "(", ")"]
    try:
        for item in to_replace:
            phone_no = phone_no.replace(item, "")
        return phone_no
    except:
        return phone_no

In [201]:
talent_data['phone_number'] = talent_data['phone_number'].apply(clean_phone_numbers)

In [202]:
#clean_phone_numbers(talent_data["phone_number"][0])

In [203]:
talent_data[talent_data["invited_by"].isna()].isna().sum()

id                0
filename          0
name              0
gender           18
dob              22
email            34
city              9
address           9
postcode          9
phone_number     48
uni              16
degree           16
invited_date    557
month           557
invited_by      557
dtype: int64

In [204]:
#talent_data["month"].unique()

In [205]:
#talent_data["filename"].unique()

In [206]:
def clean_month(month_name):
    print(month_name)
    if month_name:
        month_name2 = month_name[:-4].strip()
        year = month_name[-4:].strip()
        month_name2 = month_name2.capitalize()
        if month_name2 == "Sept":
            month_name2 = "September"
        cleaned_month = month_name2 + '-' + year
        return cleaned_month
    else:
        return month_name

In [207]:
talent_data['month'] = talent_data['month'].apply(lambda x: clean_month(x) if (np.all(pd.notnull(x))) else x)

April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
April 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
AUGUST 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
DECEMBER 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
February 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019
January 2019

In [208]:
talent_data["month"][3] is np.nan

True

In [209]:
#talent_data

## Sparta Day Column

In [210]:
def combine_date_and_month(invited_day, month):
    try:
        invited_date = str(int(invited_day)) + '-' + month
        return_date = datetime.datetime.strptime(invited_date, '%d-%B-%Y').date()
        return return_date
    except:
        return month

In [211]:
talent_data['sparta_day_date'] = talent_data.apply(lambda x : combine_date_and_month(x['invited_date'], x['month']), axis = 1)

In [212]:
talent_data

,id,filename,name,gender,dob,email,city,address,postcode,phone_number,uni,degree,invited_date,month,invited_by,sparta_day_date
0,1,April2019,Esme Trusslove,Female,04/08/1994,etrusslove0@google.es,Swindon,22056 Lerdahl Avenue,SN1,+442957830228,"Saint George's Hospital Medical School, Univer...",2:1,10.0,April-2019,Bruno Bellbrook,2019-04-10
1,2,April2019,Matthaeus Audas,Male,NaN,maudas1@mapquest.com,Charlton,263 Nelson Trail,OX12,+449577280155,Keele University,2:1,30.0,April-2019,Doris Bellasis,2019-04-30
2,3,April2019,Cherey Tollfree,Female,08/12/1992,ctollfree2@netvibes.com,Weston,69 Coleman Court,GU32,+445887496002,"King's College London, University of London",2:1,25.0,April-2019,Gismo Tilling,2019-04-25
3,4,April2019,Eryn Speers,Female,NaN,espeers3@shinystat.com,Sutton,0166 Daystar Drive,CT15,+441487870613,University of Edinburgh,2:1,NaN,NaN,NaN,NaN
4,5,April2019,Theadora Berkelay,Female,03/11/1995,tberkelay4@godaddy.com,Upton,6 Mandrake Crossing,WF9,+448414683619,University of Leicester,2:1,2.0,April-2019,Stacey Broad,2019-04-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4686,416,Sept2019,Clyve Gillhespy,Male,15/12/1995,cgillhespybj@buzzfeed.com,Birmingham,33 Almo Avenue,B40,+449043432218,University of Liverpool,2:1,26.0,September-2019,Bruno Bellbrook,2019-09-26
4687,417,Sept2019,Vaclav Pietesch,Male,09/11/1994,vpieteschbk@mac.com,Whitwell,6476 Hoffman Terrace,DL10,+444556316125,Sheffield Hallam University,2:2,12.0,September-2019,Stacey Broad,2019-09-12
4688,418,Sept2019,Kassi Lucio,Female,24/04/1994,kluciobl@exblog.jp,Normanton,06 Fulton Center,LE15,+448343429323,University of Buckingham,2:1,3.0,September-2019,Fifi Eton,2019-09-03
4689,419,Sept2019,Vivianna Letty,Female,NaN,vlettybm@google.com.hk,Sheffield,78314 Fisk Plaza,S1,+445347583140,Leeds Metropolitan University,1st,19.0,September-2019,Bruno Bellbrook,2019-09-19
4690,420,Sept2019,Mercie Groger,Female,10/05/1997,mgrogerbn@timesonline.co.uk,Charlton,5 Toban Circle,OX12,+446622394688,ifs University College,3rd,12.0,September-2019,Rupert Ripple,2019-09-12

In [213]:
talent_data = talent_data.drop(['invited_date', 'month'], axis = 1)

In [214]:
for item in talent_data["dob"]:
    print(item, type(item))

04/08/1994 <class 'str'>
nan <class 'float'>
08/12/1992 <class 'str'>
nan <class 'float'>
03/11/1995 <class 'str'>
19/04/1990 <class 'str'>
22/11/1992 <class 'str'>
12/02/1992 <class 'str'>
05/07/1991 <class 'str'>
15/06/1991 <class 'str'>
11/09/1991 <class 'str'>
30/03/1997 <class 'str'>
22/06/1994 <class 'str'>
08/05/2000 <class 'str'>
23/02/1990 <class 'str'>
11/11/1998 <class 'str'>
26/05/1998 <class 'str'>
10/01/1990 <class 'str'>
22/10/1991 <class 'str'>
18/02/1998 <class 'str'>
19/04/1997 <class 'str'>
11/12/1997 <class 'str'>
15/05/1990 <class 'str'>
31/05/1999 <class 'str'>
03/12/1996 <class 'str'>
31/01/1999 <class 'str'>
11/09/1998 <class 'str'>
28/06/1991 <class 'str'>
08/05/1991 <class 'str'>
17/10/1994 <class 'str'>
07/04/1993 <class 'str'>
22/01/1991 <class 'str'>
09/09/1998 <class 'str'>
nan <class 'float'>
24/04/1990 <class 'str'>
06/09/1998 <class 'str'>
08/03/1996 <class 'str'>
09/08/1995 <class 'str'>
03/07/1992 <class 'str'>
08/09/1999 <class 'str'>
11/03/1992 <class 'str'>
25/06/1991 <class 'str'>
02/07/1992 <class 'str'>
27/12/1991 <class 'str'>
20/08/1996 <class 'str'>
18/02/1990 <class 'str'>
24/01/1998 <class 'str'>
07/11/1998 <class 'str'>
24/04/1998 <class 'str'>
30/03/1993 <class 'str'>
11/09/1995 <class 'str'>
06/09/2000 <class 'str'>
15/04/1990 <class 'str'>
10/01/2000 <class 'str'>
01/04/2000 <class 'str'>
17/01/1991 <class 'str'>
16/08/1997 <class 'str'>
09/06/1993 <class 'str'>
21/12/1994 <class 'str'>
05/03/1995 <class 'str'>
19/08/1994 <class 'str'>
nan <class 'float'>
07/07/1990 <class 'str'>
09/10/2000 <class 'str'>
03/03/1995 <class 'str'>
27/10/1992 <class 'str'>
13/03/2000 <class 'str'>
14/06/1995 <class 'str'>
19/01/1993 <class 'str'>
26/01/1995 <class 'str'>
13/04/1999 <class 'str'>
12/11/1990 <class 'str'>
20/01/1998 <class 'str'>
12/01/1990 <class 'str'>
22/04/1990 <class 'str'>
19/03/1999 <class 'str'>
24/10/1998 <class 'str'>
25/03/1995 <class 'str'>
03/10/1993 <class 'str'>
22/11/1995 <class 'str'>
20/11/1995 <class 'str'>
12/07/1993 <class 'str'>
29/10/1995 <class 'str'>
16/04/1991 <class 'str'>
28/10/1999 <class 'str'>
05/10/1999 <class 'str'>
16/08/1991 <class 'str'>
13/09/1993 <class 'str'>
08/11/1995 <class 'str'>
10/09/1998 <class 'str'>
25/04/1993 <class 'str'>
nan <class 'float'>
11/04/1993 <class 'str'>
29/06/2000 <class 'str'>
22/09/1993 <class 'str'>
08/11/1993 <class 'str'>
08/02/1993 <class 'str'>
17/08/1999 <class 'str'>
08/01/1994 <class 'str'>
21/09/2000 <class 'str'>
nan <class 'float'>
13/03/1999 <class 'str'>
05/07/1991 <class 'str'>
13/08/1992 <class 'str'>
19/07/1997 <class 'str'>
15/04/1993 <class 'str'>
05/10/1998 <class 'str'>
05/10/1991 <class 'str'>
02/05/1995 <class 'str'>
24/03/1992 <class 'str'>
22/12/1991 <class 'str'>
17/02/1996 <class 'str'>
30/01/1991 <class 'str'>
28/02/1996 <class 'str'>
08/08/1990 <class 'str'>
23/04/1991 <class 'str'>
25/07/1998 <class 'str'>
29/06/1996 <class 'str'>
22/12/1993 <class 'str'>
13/05/1993 <class 'str'>
28/08/1998 <class 'str'>
16/12/1994 <class 'str'>
13/04/1998 <class 'str'>
07/09/2000 <class 'str'>
06/03/1999 <class 'str'>
22/12/1997 <class 'str'>
23/09/1998 <class 'str'>
15/06/1994 <class 'str'>
05/12/1998 <class 'str'>
12/10/1997 <class 'str'>
14/06/2000 <class 'str'>
30/07/1992 <class 'str'>
25/01/1990 <class 'str'>
21/06/1995 <class 'str'>
28/09/1991 <class 'str'>
10/05/1991 <class 'str'>
14/09/1991 <class 'str'>
16/10/1993 <class 'str'>
02/11/1993 <class 'str'>
12/03/1990 <class 'str'>
14/06/1990 <class 'str'>
07/11/1997 <class 'str'>
09/05/1997 <class 'str'>
18/05/1999 <class 'str'>
05/06/1994 <class 'str'>
nan <class 'float'>
05/11/1992 <class 'str'>
02/12/1999 <class 'str'>
27/05/1992 <class 'str'>
02/10/1993 <class 'str'>
27/11/1991 <class 'str'>
25/04/2000 <class 'str'>
05/04/1999 <class 'str'>
nan <class 'float'>
31/12/1992 <class 'str'>
31/08/1998 <class 'str'>
24/01/1992 <class 'str'>
01/02/1994 <class 'str'>
21/01/1992 <class 'str'>
05/05/1992 <class 'str'>
11/03/1998 <class 'str'>
05/06/1994 <class 'str'>
10/11/1998 <class 'str'>
16/08/1992 <class 'str'>
27/07/1993 <class 'str'>
24/01/1996 <class 'str'>
29/01/1999 <class 'str'>
nan <class 'float'>
26/12/1996 <class 'str'>
11/10/1997 <class 'str'>
04/08/1990 <class 'str'>
18/01/1994 <class 'str'>
02/03/1995 <class 'str'>
26/01/1992 <class 'str'>
26/09/1994 <class 'str'>
13/03/1990 <class 'str'>
19/03/1996 <class 'str'>
15/08/1998 <class 'str'>
16/08/1999 <class 'str'>
nan <class 'float'>
06/06/1999 <class 'str'>
13/05/2000 <class 'str'>
12/02/1994 <class 'str'>
31/08/1997 <class 'str'>
24/07/2000 <class 'str'>
01/07/1992 <class 'str'>
10/11/1993 <class 'str'>
30/04/1996 <class 'str'>
02/05/1991 <class 'str'>
03/03/2000 <class 'str'>
22/10/2000 <class 'str'>
02/10/2000 <class 'str'>
10/12/1999 <class 'str'>
11/05/2000 <class 'str'>
23/12/1997 <class 'str'>
28/01/1997 <class 'str'>
21/05/1996 <class 'str'>
12/04/1998 <class 'str'>
nan <class 'float'>
13/02/1990 <class 'str'>
01/12/1994 <class 'str'>
11/12/1994 <class 'str'>
28/09/1997 <class 'str'>
09/01/1996 <class 'str'>
24/02/1993 <class 'str'>
15/08/1993 <class 'str'>
27/12/1994 <class 'str'>
12/12/1997 <class 'str'>
27/10/1994 <class 'str'>
05/08/1990 <class 'str'>
24/02/1995 <class 'str'>
06/12/1991 <class 'str'>
28/10/1996 <class 'str'>
26/10/1993 <class 'str'>
11/09/1993 <class 'str'>
22/01/1991 <class 'str'>
26/05/1991 <class 'str'>
02/01/1992 <class 'str'>
18/10/1999 <class 'str'>
14/04/2000 <class 'str'>
01/04/1996 <class 'str'>
12/04/1998 <class 'str'>
28/07/1990 <class 'str'>
07/03/1994 <class 'str'>
05/04/1992 <class 'str'>
19/06/1998 <class 'str'>
15/03/1990 <class 'str'>
19/07/1991 <class 'str'>
17/09/2000 <class 'str'>
01/09/1995 <class 'str'>
16/10/1993 <class 'str'>
08/04/1991 <class 'str'>
05/04/1992 <class 'str'>
05/06/1999 <class 'str'>
14/05/1991 <class 'str'>
22/12/1990 <class 'str'>
10/07/1998 <class 'str'>
31/07/1994 <class 'str'>
03/03/1999 <class 'str'>
12/11/1993 <class 'str'>
15/04/1993 <class 'str'>
01/09/1996 <class 'str'>
07/05/1999 <class 'str'>
14/09/2000 <class 'str'>
29/01/2000 <class 'str'>
04/06/1994 <class 'str'>
28/04/1992 <class 'str'>
04/01/1998 <class 'str'>
29/08/1998 <class 'str'>
20/02/1995 <class 'str'>
30/07/1997 <class 'str'>
19/11/2000 <class 'str'>
18/10/1998 <class 'str'>
03/02/2000 <class 'str'>
06/06/1995 <class 'str'>
27/01/1998 <class 'str'>
19/11/1991 <class 'str'>
19/06/1991 <class 'str'>
12/05/1994 <class 'str'>
14/06/1992 <class 'str'>
02/03/1995 <class 'str'>
24/03/1993 <class 'str'>
15/12/1994 <class 'str'>
03/02/1994 <class 'str'>
02/12/2000 <class 'str'>
17/12/2000 <class 'str'>
16/06/1993 <class 'str'>
11/11/1993 <class 'str'>
27/04/1995 <class 'str'>
09/05/1999 <class 'str'>
29/05/1990 <class 'str'>
29/06/1998 <class 'str'>
13/04/1996 <class 'str'>
01/07/1992 <class 'str'>
19/06/1999 <class 'str'>
05/05/2000 <class 'str'>
02/07/1995 <class 'str'>
06/10/1994 <class 'str'>
09/09/1990 <class 'str'>
05/04/1990 <class 'str'>
22/08/1996 <class 'str'>
nan <class 'float'>
17/06/1997 <class 'str'>
17/06/1999 <class 'str'>
27/05/1994 <class 'str'>
17/06/1997 <class 'str'>
04/12/1991 <class 'str'>
13/04/1998 <class 'str'>
nan <class 'float'>
09/06/1998 <class 'str'>
17/11/1991 <class 'str'>
nan <class 'float'>
12/11/1998 <class 'str'>
23/01/1990 <class 'str'>
03/11/1999 <class 'str'>
07/10/1990 <class 'str'>
04/10/1998 <class 'str'>
03/12/1997 <class 'str'>
16/01/1999 <class 'str'>
13/02/1996 <class 'str'>
08/03/1997 <class 'str'>
05/12/1998 <class 'str'>
31/12/1995 <class 'str'>
17/09/1994 <class 'str'>
27/05/1998 <class 'str'>
08/07/1997 <class 'str'>
14/03/1995 <class 'str'>
31/08/1997 <class 'str'>
30/07/1992 <class 'str'>
11/10/1999 <class 'str'>
22/06/1999 <class 'str'>
23/04/1992 <class 'str'>
nan <class 'float'>
12/06/1990 <class 'str'>
30/08/1996 <class 'str'>
31/08/1992 <class 'str'>
20/05/1996 <class 'str'>
07/04/1995 <class 'str'>
13/06/1996 <class 'str'>
06/07/1998 <class 'str'>
26/10/1992 <class 'str'>
31/05/1993 <class 'str'>
23/06/1992 <class 'str'>
nan <class 'float'>
21/04/1996 <class 'str'>
06/06/1995 <class 'str'>
nan <class 'float'>
21/10/1990 <class 'str'>
06/12/1996 <class 'str'>
09/02/2000 <class 'str'>
20/04/1997 <class 'str'>
17/12/1992 <class 'str'>
05/12/1995 <class 'str'>
nan <class 'float'>
30/10/1996 <class 'str'>
13/05/1999 <class 'str'>
29/04/1997 <class 'str'>
17/12/1990 <class 'str'>
04/12/1991 <class 'str'>
12/03/1991 <class 'str'>
20/12/1999 <class 'str'>
28/05/1995 <class 'str'>
07/11/1992 <class 'str'>
23/01/1996 <class 'str'>
08/12/1997 <class 'str'>
29/11/1996 <class 'str'>
26/07/1990 <class 'str'>
14/02/1990 <class 'str'>
16/03/1996 <class 'str'>
30/01/1990 <class 'str'>
27/04/1996 <class 'str'>
11/11/1994 <class 'str'>
08/01/1995 <class 'str'>
05/06/1990 <class 'str'>
19/07/1992 <class 'str'>
07/07/1996 <class 'str'>
22/07/1995 <class 'str'>
06/05/1997 <class 'str'>
20/06/1997 <class 'str'>
25/12/1997 <class 'str'>
30/03/1996 <class 'str'>
21/10/1997 <class 'str'>
09/09/1996 <class 'str'>
30/10/1991 <class 'str'>
24/08/1993 <class 'str'>
21/03/1993 <class 'str'>
13/06/1999 <class 'str'>
23/02/1997 <class 'str'>
25/09/1999 <class 'str'>
19/05/1997 <class 'str'>
12/05/1998 <class 'str'>
31/12/1994 <class 'str'>
29/09/1996 <class 'str'>
05/11/1994 <class 'str'>
24/11/1990 <class 'str'>
08/11/1994 <class 'str'>
19/03/1995 <class 'str'>
23/11/1993 <class 'str'>
21/04/1991 <class 'str'>
25/07/1992 <class 'str'>
26/08/1995 <class 'str'>
05/12/1996 <class 'str'>
nan <class 'float'>
07/01/1990 <class 'str'>
15/12/2000 <class 'str'>
28/04/1990 <class 'str'>
02/11/1994 <class 'str'>
23/01/1991 <class 'str'>
10/03/1991 <class 'str'>
nan <class 'float'>
17/01/1992 <class 'str'>
05/03/1992 <class 'str'>
08/10/1993 <class 'str'>
nan <class 'float'>
18/10/1992 <class 'str'>
20/09/1993 <class 'str'>
13/06/1992 <class 'str'>
08/03/1991 <class 'str'>
11/09/1994 <class 'str'>
nan <class 'float'>
nan <class 'float'>
26/07/1990 <class 'str'>
29/12/1993 <class 'str'>
08/05/1995 <class 'str'>
18/07/2000 <class 'str'>
05/09/1993 <class 'str'>
12/02/1992 <class 'str'>
25/01/1997 <class 'str'>
17/01/1994 <class 'str'>
30/01/1997 <class 'str'>
17/10/1995 <class 'str'>
28/11/1993 <class 'str'>
04/12/1992 <class 'str'>
24/11/1993 <class 'str'>
12/10/1999 <class 'str'>
20/02/1998 <class 'str'>
nan <class 'float'>
01/08/1997 <class 'str'>
09/07/1993 <class 'str'>
28/08/1998 <class 'str'>
13/01/1993 <class 'str'>
27/11/1997 <class 'str'>
29/09/1993 <class 'str'>
07/02/1992 <class 'str'>
29/09/1990 <class 'str'>
28/04/1992 <class 'str'>
06/09/1992 <class 'str'>
11/02/1999 <class 'str'>
22/12/1992 <class 'str'>
02/01/1990 <class 'str'>
25/05/1996 <class 'str'>
20/04/2000 <class 'str'>
27/08/1991 <class 'str'>
10/11/1999 <class 'str'>
21/11/1997 <class 'str'>
17/12/1990 <class 'str'>
nan <class 'float'>
28/11/1999 <class 'str'>
nan <class 'float'>
07/09/1991 <class 'str'>
13/03/1991 <class 'str'>
nan <class 'float'>
13/02/1995 <class 'str'>
nan <class 'float'>
22/05/1997 <class 'str'>
29/06/1996 <class 'str'>
28/02/1997 <class 'str'>
23/02/1990 <class 'str'>
09/11/1993 <class 'str'>
14/09/1993 <class 'str'>
01/03/1999 <class 'str'>
05/10/1995 <class 'str'>
27/09/1991 <class 'str'>
30/11/1993 <class 'str'>
17/04/2000 <class 'str'>
05/04/1992 <class 'str'>
31/01/1994 <class 'str'>
25/05/1990 <class 'str'>
25/01/1998 <class 'str'>
08/04/1998 <class 'str'>
17/01/2000 <class 'str'>
09/09/1997 <class 'str'>
12/11/2000 <class 'str'>
06/08/1996 <class 'str'>
18/08/1991 <class 'str'>
05/05/1993 <class 'str'>
30/08/1992 <class 'str'>
09/07/1996 <class 'str'>
29/03/1996 <class 'str'>
15/04/1990 <class 'str'>
26/04/1990 <class 'str'>
25/10/1999 <class 'str'>
12/10/1992 <class 'str'>
12/02/2000 <class 'str'>
22/08/2000 <class 'str'>
23/11/1991 <class 'str'>
24/11/2000 <class 'str'>
04/01/2000 <class 'str'>
18/03/1994 <class 'str'>
04/03/1994 <class 'str'>
16/03/1993 <class 'str'>
27/09/1999 <class 'str'>
21/10/1998 <class 'str'>
29/01/1994 <class 'str'>
17/01/1995 <class 'str'>
16/08/2000 <class 'str'>
09/03/1995 <class 'str'>
01/05/1994 <class 'str'>
25/02/1994 <class 'str'>
10/05/2000 <class 'str'>
11/07/1996 <class 'str'>
26/08/1997 <class 'str'>
01/05/1996 <class 'str'>
07/10/1998 <class 'str'>
26/02/1992 <class 'str'>
20/02/1996 <class 'str'>
27/04/1990 <class 'str'>
14/07/1992 <class 'str'>
19/03/1994 <class 'str'>
03/10/1991 <class 'str'>
08/06/1991 <class 'str'>
12/08/1995 <class 'str'>
24/02/1994 <class 'str'>
17/10/1993 <class 'str'>
14/09/1997 <class 'str'>
11/02/1998 <class 'str'>
17/12/1994 <class 'str'>
10/08/2000 <class 'str'>
04/08/1997 <class 'str'>
26/03/1998 <class 'str'>
16/06/1997 <class 'str'>
16/01/1993 <class 'str'>
27/11/1995 <class 'str'>
23/06/1994 <class 'str'>
19/06/1993 <class 'str'>
02/11/1997 <class 'str'>
15/12/2000 <class 'str'>
07/10/1994 <class 'str'>
01/03/1991 <class 'str'>
nan <class 'float'>
15/08/1998 <class 'str'>
11/12/1991 <class 'str'>
nan <class 'float'>
20/11/1992 <class 'str'>
28/10/1998 <class 'str'>
07/08/1995 <class 'str'>
20/12/1999 <class 'str'>
28/08/1997 <class 'str'>
20/09/2000 <class 'str'>
10/01/2000 <class 'str'>
17/10/1992 <class 'str'>
08/01/1996 <class 'str'>
01/12/1999 <class 'str'>
18/03/1996 <class 'str'>
08/11/1991 <class 'str'>
05/11/1999 <class 'str'>
24/05/1996 <class 'str'>
04/07/2000 <class 'str'>
05/03/1996 <class 'str'>
04/07/1994 <class 'str'>
19/03/1991 <class 'str'>
02/07/1990 <class 'str'>
17/04/1998 <class 'str'>
18/08/1990 <class 'str'>
09/08/1997 <class 'str'>
06/05/1993 <class 'str'>
24/06/1992 <class 'str'>
nan <class 'float'>
02/08/1994 <class 'str'>
05/09/1997 <class 'str'>
21/08/1998 <class 'str'>
07/11/1997 <class 'str'>
19/12/1994 <class 'str'>
22/05/1998 <class 'str'>
18/03/1993 <class 'str'>
05/04/1994 <class 'str'>
29/09/1993 <class 'str'>
nan <class 'float'>
11/03/1993 <class 'str'>
18/04/1999 <class 'str'>
09/06/1998 <class 'str'>
29/08/1993 <class 'str'>
10/01/1991 <class 'str'>
09/01/2000 <class 'str'>
nan <class 'float'>
03/04/1990 <class 'str'>
10/02/1999 <class 'str'>
17/02/1996 <class 'str'>
25/03/1991 <class 'str'>
25/03/1990 <class 'str'>
15/09/1990 <class 'str'>
27/04/1992 <class 'str'>
07/04/1997 <class 'str'>
29/06/1999 <class 'str'>
03/10/1992 <class 'str'>
nan <class 'float'>
10/01/1992 <class 'str'>
23/07/1996 <class 'str'>
02/05/1994 <class 'str'>
14/01/1999 <class 'str'>
03/05/1996 <class 'str'>
12/08/1994 <class 'str'>
13/10/1991 <class 'str'>
17/09/1993 <class 'str'>
26/03/1998 <class 'str'>
17/02/1992 <class 'str'>
03/07/1995 <class 'str'>
13/07/1991 <class 'str'>
20/02/1997 <class 'str'>
04/08/1998 <class 'str'>
02/07/1991 <class 'str'>
10/06/1990 <class 'str'>
22/12/1994 <class 'str'>
15/02/1990 <class 'str'>
19/03/1996 <class 'str'>
24/06/1999 <class 'str'>
17/11/1993 <class 'str'>
19/01/1990 <class 'str'>
15/09/1996 <class 'str'>
07/04/1996 <class 'str'>
nan <class 'float'>
02/10/1991 <class 'str'>
05/11/1994 <class 'str'>
21/11/1993 <class 'str'>
18/06/1998 <class 'str'>
19/02/2000 <class 'str'>
03/10/1998 <class 'str'>
29/08/1996 <class 'str'>
04/08/1994 <class 'str'>
30/11/1999 <class 'str'>
29/06/1994 <class 'str'>
12/01/1990 <class 'str'>
nan <class 'float'>
02/05/1993 <class 'str'>
27/01/1992 <class 'str'>
27/10/1991 <class 'str'>
15/06/1999 <class 'str'>
23/01/1990 <class 'str'>
25/03/1990 <class 'str'>
13/01/1998 <class 'str'>
12/03/1992 <class 'str'>
26/11/1996 <class 'str'>
01/02/1990 <class 'str'>
29/12/1993 <class 'str'>
08/10/2000 <class 'str'>
11/01/1999 <class 'str'>
12/07/1994 <class 'str'>
03/01/1997 <class 'str'>
26/01/1997 <class 'str'>
nan <class 'float'>
27/05/1990 <class 'str'>
02/01/1998 <class 'str'>
21/12/1997 <class 'str'>
16/06/1991 <class 'str'>
28/01/1997 <class 'str'>
30/06/1995 <class 'str'>
12/07/1992 <class 'str'>
14/06/1996 <class 'str'>
23/01/2000 <class 'str'>
24/07/1990 <class 'str'>
14/02/1991 <class 'str'>
20/11/1994 <class 'str'>
17/06/1992 <class 'str'>
06/05/1990 <class 'str'>
12/09/1998 <class 'str'>
25/08/1999 <class 'str'>
29/07/1993 <class 'str'>
nan <class 'float'>
18/02/1998 <class 'str'>
13/11/1992 <class 'str'>
12/08/1993 <class 'str'>
11/03/2000 <class 'str'>
05/01/2000 <class 'str'>
25/08/1991 <class 'str'>
28/01/1990 <class 'str'>
15/06/2000 <class 'str'>
28/02/1995 <class 'str'>
26/05/1998 <class 'str'>
23/05/1992 <class 'str'>
06/05/1993 <class 'str'>
03/03/1995 <class 'str'>
07/09/1995 <class 'str'>
21/01/1995 <class 'str'>
06/05/1995 <class 'str'>
04/03/1995 <class 'str'>
29/07/1995 <class 'str'>
nan <class 'float'>
16/05/1999 <class 'str'>
08/05/1993 <class 'str'>
28/11/1998 <class 'str'>
10/11/1991 <class 'str'>
01/04/1995 <class 'str'>
06/07/1993 <class 'str'>
05/05/1995 <class 'str'>
06/09/1990 <class 'str'>
07/08/1999 <class 'str'>
12/03/1996 <class 'str'>
04/01/1993 <class 'str'>
25/01/1996 <class 'str'>
17/01/1993 <class 'str'>
10/08/1997 <class 'str'>
23/06/1998 <class 'str'>
12/03/1997 <class 'str'>
13/02/1992 <class 'str'>
19/08/1998 <class 'str'>
30/12/1997 <class 'str'>
11/08/1993 <class 'str'>
08/01/1999 <class 'str'>
07/01/2000 <class 'str'>
03/06/1995 <class 'str'>
21/02/1998 <class 'str'>
14/06/1996 <class 'str'>
26/01/1999 <class 'str'>
08/04/1994 <class 'str'>
09/10/1995 <class 'str'>
16/10/1995 <class 'str'>
18/05/1999 <class 'str'>
nan <class 'float'>
24/10/1993 <class 'str'>
21/09/2000 <class 'str'>
16/11/1994 <class 'str'>
09/09/1992 <class 'str'>
16/05/1992 <class 'str'>
10/03/1993 <class 'str'>
13/09/1993 <class 'str'>
19/09/2000 <class 'str'>
07/01/1990 <class 'str'>
nan <class 'float'>
nan <class 'float'>
31/08/1998 <class 'str'>
14/07/1996 <class 'str'>
05/10/1995 <class 'str'>
30/12/1994 <class 'str'>
26/09/1991 <class 'str'>
29/01/1998 <class 'str'>
30/09/1994 <class 'str'>
29/09/1996 <class 'str'>
09/07/1992 <class 'str'>
14/01/1995 <class 'str'>
07/08/1990 <class 'str'>
15/12/2000 <class 'str'>
nan <class 'float'>
16/03/2000 <class 'str'>
09/10/1992 <class 'str'>
23/04/1993 <class 'str'>
30/04/1990 <class 'str'>
13/01/1994 <class 'str'>
10/03/1993 <class 'str'>
22/10/1994 <class 'str'>
16/05/1998 <class 'str'>
19/03/1993 <class 'str'>
26/09/1993 <class 'str'>
01/12/1999 <class 'str'>
14/12/1994 <class 'str'>
14/11/2000 <class 'str'>
24/06/2000 <class 'str'>
01/04/1990 <class 'str'>
28/11/1997 <class 'str'>
02/03/1990 <class 'str'>
19/10/1994 <class 'str'>
02/08/1990 <class 'str'>
03/01/1999 <class 'str'>
10/10/1991 <class 'str'>
16/05/2000 <class 'str'>
26/01/1996 <class 'str'>
nan <class 'float'>
06/07/1995 <class 'str'>
nan <class 'float'>
04/06/1993 <class 'str'>
31/01/1993 <class 'str'>
16/10/1994 <class 'str'>
29/03/1999 <class 'str'>
22/12/1996 <class 'str'>
28/07/1994 <class 'str'>
13/05/1994 <class 'str'>
15/06/1992 <class 'str'>
26/08/1997 <class 'str'>
15/10/1999 <class 'str'>
15/06/1993 <class 'str'>
21/07/2000 <class 'str'>
10/10/1997 <class 'str'>
26/08/1993 <class 'str'>
16/10/1990 <class 'str'>
10/12/1995 <class 'str'>
26/05/1993 <class 'str'>
15/06/1995 <class 'str'>
28/01/1996 <class 'str'>
22/05/2000 <class 'str'>
09/06/1992 <class 'str'>
19/11/1998 <class 'str'>
07/02/1994 <class 'str'>
10/08/1992 <class 'str'>
18/04/1992 <class 'str'>
29/09/1995 <class 'str'>
28/02/1998 <class 'str'>
12/04/1994 <class 'str'>
24/12/1999 <class 'str'>
27/01/1992 <class 'str'>
25/01/1991 <class 'str'>
nan <class 'float'>
19/12/1995 <class 'str'>
30/12/1997 <class 'str'>
18/08/1992 <class 'str'>
02/05/1998 <class 'str'>
03/01/1991 <class 'str'>
05/02/1990 <class 'str'>
02/12/1999 <class 'str'>
21/12/1991 <class 'str'>
21/09/1999 <class 'str'>
29/04/1996 <class 'str'>
26/07/1999 <class 'str'>
15/11/1994 <class 'str'>
18/12/1999 <class 'str'>
04/07/1996 <class 'str'>
29/03/2000 <class 'str'>
10/04/2000 <class 'str'>
05/09/1991 <class 'str'>
17/06/1998 <class 'str'>
11/01/1994 <class 'str'>
30/04/1993 <class 'str'>
04/06/1994 <class 'str'>
13/01/1996 <class 'str'>
09/01/1999 <class 'str'>
09/03/2000 <class 'str'>
23/06/1997 <class 'str'>
08/05/1996 <class 'str'>
17/02/1991 <class 'str'>
18/09/1991 <class 'str'>
27/01/1997 <class 'str'>

In [215]:
def dobs_to_datetime(date_ofb):
    try:
        strp_dob = datetime.datetime.strptime(date_ofb, '%d/%m/%Y').date()
        return strp_dob
    except:
        return date_ofb

In [216]:
talent_data["dob"] = talent_data["dob"].apply(dobs_to_datetime)

In [217]:
talent_data["degree"].unique()

array(['2:1', '1st', '3rd', nan, '2:2'], dtype=object)

## Capitalising the street addresses

In [218]:
def capital_addresses(address_str):
    try:
        address_str = address_str.title()
        return address_str
    except:
        return address_str

In [219]:
talent_data['address'] = talent_data['address'].apply(capital_addresses)

In [220]:
talent_data

,id,filename,name,gender,dob,email,city,address,postcode,phone_number,uni,degree,invited_by,sparta_day_date
0,1,April2019,Esme Trusslove,Female,1994-08-04,etrusslove0@google.es,Swindon,22056 Lerdahl Avenue,SN1,+442957830228,"Saint George's Hospital Medical School, Univer...",2:1,Bruno Bellbrook,2019-04-10
1,2,April2019,Matthaeus Audas,Male,NaN,maudas1@mapquest.com,Charlton,263 Nelson Trail,OX12,+449577280155,Keele University,2:1,Doris Bellasis,2019-04-30
2,3,April2019,Cherey Tollfree,Female,1992-12-08,ctollfree2@netvibes.com,Weston,69 Coleman Court,GU32,+445887496002,"King's College London, University of London",2:1,Gismo Tilling,2019-04-25
3,4,April2019,Eryn Speers,Female,NaN,espeers3@shinystat.com,Sutton,0166 Daystar Drive,CT15,+441487870613,University of Edinburgh,2:1,NaN,NaN
4,5,April2019,Theadora Berkelay,Female,1995-11-03,tberkelay4@godaddy.com,Upton,6 Mandrake Crossing,WF9,+448414683619,University of Leicester,2:1,Stacey Broad,2019-04-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4686,416,Sept2019,Clyve Gillhespy,Male,1995-12-15,cgillhespybj@buzzfeed.com,Birmingham,33 Almo Avenue,B40,+449043432218,University of Liverpool,2:1,Bruno Bellbrook,2019-09-26
4687,417,Sept2019,Vaclav Pietesch,Male,1994-11-09,vpieteschbk@mac.com,Whitwell,6476 Hoffman Terrace,DL10,+444556316125,Sheffield Hallam University,2:2,Stacey Broad,2019-09-12
4688,418,Sept2019,Kassi Lucio,Female,1994-04-24,kluciobl@exblog.jp,Normanton,06 Fulton Center,LE15,+448343429323,University of Buckingham,2:1,Fifi Eton,2019-09-03
4689,419,Sept2019,Vivianna Letty,Female,NaN,vlettybm@google.com.hk,Sheffield,78314 Fisk Plaza,S1,+445347583140,Leeds Metropolitan University,1st,Bruno Bellbrook,2019-09-19
4690,420,Sept2019,Mercie Groger,Female,1997-05-10,mgrogerbn@timesonline.co.uk,Charlton,5 Toban Circle,OX12,+446622394688,ifs University College,3rd,Rupert Ripple,2019-09-12

In [221]:
talent_data.dtypes

id                  int64
filename           object
name               object
gender             object
dob                object
email              object
city               object
address            object
postcode           object
phone_number       object
uni                object
degree             object
invited_by         object
sparta_day_date    object
dtype: object

## Removing the whitespace

In [227]:
def whitespace_delete(column):
    try:
        return column.strip()
    except:
        return column

In [228]:
for column in list(talent_data.columns):
    talent_data[column] = talent_data[column].apply(whitespace_delete)

In [229]:
talent_data

,id,filename,name,gender,dob,email,city,address,postcode,phone_number,uni,degree,invited_by,sparta_day_date
0,1,April2019,Esme Trusslove,Female,1994-08-04,etrusslove0@google.es,Swindon,22056 Lerdahl Avenue,SN1,+442957830228,"Saint George's Hospital Medical School, Univer...",2:1,Bruno Bellbrook,2019-04-10
1,2,April2019,Matthaeus Audas,Male,NaN,maudas1@mapquest.com,Charlton,263 Nelson Trail,OX12,+449577280155,Keele University,2:1,Doris Bellasis,2019-04-30
2,3,April2019,Cherey Tollfree,Female,1992-12-08,ctollfree2@netvibes.com,Weston,69 Coleman Court,GU32,+445887496002,"King's College London, University of London",2:1,Gismo Tilling,2019-04-25
3,4,April2019,Eryn Speers,Female,NaN,espeers3@shinystat.com,Sutton,0166 Daystar Drive,CT15,+441487870613,University of Edinburgh,2:1,NaN,NaN
4,5,April2019,Theadora Berkelay,Female,1995-11-03,tberkelay4@godaddy.com,Upton,6 Mandrake Crossing,WF9,+448414683619,University of Leicester,2:1,Stacey Broad,2019-04-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4686,416,Sept2019,Clyve Gillhespy,Male,1995-12-15,cgillhespybj@buzzfeed.com,Birmingham,33 Almo Avenue,B40,+449043432218,University of Liverpool,2:1,Bruno Bellbrook,2019-09-26
4687,417,Sept2019,Vaclav Pietesch,Male,1994-11-09,vpieteschbk@mac.com,Whitwell,6476 Hoffman Terrace,DL10,+444556316125,Sheffield Hallam University,2:2,Stacey Broad,2019-09-12
4688,418,Sept2019,Kassi Lucio,Female,1994-04-24,kluciobl@exblog.jp,Normanton,06 Fulton Center,LE15,+448343429323,University of Buckingham,2:1,Fifi Eton,2019-09-03
4689,419,Sept2019,Vivianna Letty,Female,NaN,vlettybm@google.com.hk,Sheffield,78314 Fisk Plaza,S1,+445347583140,Leeds Metropolitan University,1st,Bruno Bellbrook,2019-09-19
4690,420,Sept2019,Mercie Groger,Female,1997-05-10,mgrogerbn@timesonline.co.uk,Charlton,5 Toban Circle,OX12,+446622394688,ifs University College,3rd,Rupert Ripple,2019-09-12